# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
markdown:            kramdown

# Setup
title:               Forward
tagline:             'Yu-Hsiang Huang'
description:         'It is the place to write down all that I have seen.'
url:                 https://yuhsianghuang.github.io/blog
baseurl:             '/blog'
paginate:            5

# About/contact
author:
  name:              Yu-Hsiang Huang
  url:               https://twitter.com/
  email:             yhhuang@nlg.csie.ntu.edu.tw

# Custom vars
version:             1.0.0
